/* Generated by Yosys 0.67+42 (git sha1 6f7123d1d-dirty, Release, Clang /usr/bin/clang++ 18.1.8) */

(* top =  1  *)
(* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:2.1-39.10" *)
module custdiveg(IN, OUT, clk);
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:4.24-4.26" *)
  input [127:0] IN;
  wire [127:0] IN;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:5.21-5.24" *)
  output [127:0] OUT;
  wire [127:0] OUT;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:6.16-6.19" *)
  input clk;
  wire clk;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:11.13-11.14" *)
  wire [15:0] O;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:12.5-12.7" *)
  reg R0;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:12.9-12.13" *)
  reg R0_1;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:34.1-37.4" *)
  always @(posedge clk)
    R0 <= R0_1;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:34.1-37.4" *)
  always @(posedge clk)
    R0_1 <= IN[0];
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:27.3-32.2" *)
  custdiv #(
    .MODE_CUSTDIV(32'sd1)
  ) cdiv (
    .C(clk),
    .I0(IN[15:0]),
    .I1(IN[47:32]),
    .Q(O)
  );
  assign OUT = { O, 110'hxxxxxxxxxxxxxxxxxxxxxxxxxxxx, R0, R0_1 };
endmodule
