/* Generated by Yosys 0.67+42 (git sha1 6f7123d1d-dirty, Release, Clang /usr/bin/clang++ 18.1.8) */

(* top =  1  *)
(* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:2.1-39.10" *)
module custdiveg(IN, OUT, clk);
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:4.19-4.21" *)
  input [127:0] IN;
  wire [127:0] IN;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:5.21-5.24" *)
  output [127:0] OUT;
  wire [127:0] OUT;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:6.11-6.14" *)
  input clk;
  wire clk;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:10.14-10.15" *)
  wire [15:0] O;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:11.9-11.11" *)
  reg R0;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:11.13-11.17" *)
  reg R0_1;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:32.2-35.5" *)
  always @(posedge clk)
    R0 <= R0_1;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:32.2-35.5" *)
  always @(posedge clk)
    R0_1 <= IN[0];
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:25.7-30.6" *)
  custdiv #(
    .MODE_CUSTDIV(32'sd1)
  ) cdiv (
    .C(clk),
    .I0(IN[15:0]),
    .I1(IN[47:32]),
    .Q(O)
  );
  assign OUT = { O, 110'hxxxxxxxxxxxxxxxxxxxxxxxxxxxx, R0, R0_1 };
endmodule
